print("if you open this u want to know what this does")
print("make sure the extension is already in the same folder")
dofile('extension.lua')
wait(1)
print("as you can see it adds the wait function")
wait(0.5)
print('you can also write it as sleep')
sleep(0.5)
print("you can also use decimal numbers")
wait(3)
print("lets move on to the next feature")
wait(1)
clear()
print("its the clear feature")
wait(0.5)
print('it clears the screen')
sleep(2)
print("next feature")
sleep(1.5)
clear()
print("its the input feature")
local whatprint = input("what should we print?: ")
print(whatprint)
sleep(1)
print("its asks for input simple")
wait(1)
print('last one')
print("its quit")
wait(2)
quit()